### ISSUE TITLE
Spring Boot and Spring Cloud, microservice web architectures on the JVM

### ISSUE THREAD

**Issue by ches** [bkkhack/hacknights#1]
I have an interest in learning about [Spring Boot](http://projects.spring.io/spring-boot/) for rapid development of web services with convention-over-configuration on the JVM, and [Spring Cloud](http://projects.spring.io/spring-cloud/) easily enabling many patterns and integrations for robust distributed architectures.

I need to brush up on my knowledge of modern Java for work interests, but I'm more inclined to play with [Kotlin](http://kotlinlang.org/) or [Groovy](http://groovy-lang.org/) at hack night because they're much more fun and less tedious than plain Java, and they are supported by Spring Boot. I'd prefer Kotlin because it's statically typed, but it's probably a new language for all of us so it might slow us down. If someone else is already very familiar with Groovy and/or Spring, I'd be happy to learn from you either way.

I am a beginner with these technologies (Spring frameworks in general), but I have watched a few talks already, you may want to watch them too:
- [Getting Started with Spring Boot](https://www.youtube.com/watch?v=NalZ4je7ch8)
- [Getting Started with Spring Cloud](https://www.youtube.com/watch?v=sA2eBhFTQ6Q)

Give a +1 on this ticket if you're interested in looking at these things with me at hack night!

**Comment by ches** [comment]
@nadam is this familiar territory for you?

**Comment by nadam** [comment]
I should be familiar with spring boot and microservices, since it's what my main client has switched to, but I'm not a big fan so far and haven't actually done any development myself using it. As usual it's a bit of a hype and you have to be careful to only use it when it makes sense.

**Comment by ches** [comment]
True, Spring Cloud stuff especially is overkill for a lot of situations.

**Comment by ches** [comment]
Some retrospective: I didn't spend much time with this during hack night, I get preoccupied with facilitating as an organizer…

I'll be learning these things for work interests in the coming weeks, so if anyone wants to talk about them in the future I'll be happy to, but I probably won't focus on this at next hack night so I'm closing the item.
