### ISSUE TITLE
i want to learn to code

### ISSUE THREAD

**Issue by jink82** [bkkhack/hacknights#100]

**Comment by ches** [comment]
Hi, do you have a language in mind, or a particular area you want to aim for like web development, mobile, or games? It will give people that might be able to help you a better understanding if you can explain.

We have some resources here for beginners:

https://github.com/bkkhack/resources/wiki

It may not cover everything you might wish for yet, but maybe it's a helpful first step.

**Comment by jink82** [comment]
Hi Ches,

Thanks for your resource.

Actually, i have no experience in coding but would like to learn something
that not too complicate.

I would like to learn it for web development. im not sure that it will be
good idea to start with "Python"?

Thank again
Jink

**Comment by ches** [comment]
I think Python is a good choice and there are likely some people at the hack nights who could help with it. I'll label this card as Python for now, you can change it if you change your mind (check your email for invitation to join the bkkhack GitHub team).
