### ISSUE TITLE
refactoring redux-react app

### ISSUE THREAD

**Issue by aifarfa** [bkkhack/hacknights#101]
refactoring (part of) react client app 

following [ducks modular pattern](https://github.com/erikras/ducks-modular-redux)
related libs:  react, redux, webpack, babel, es6, mocha, jsdom, nyc

all made in TDD/BDD
refactor -> run  tests -> fixed if any test failed -> start over

**Comment by ches** [comment]
I haven't done much frontend dev for a long time, but I'm curious about the functional-inpsired approaches and would like to hear experiences from people who have built apps with Redux vs. GraphQL or Falcor, or have experimented with Elm.
