### ISSUE TITLE
Clojure Spec and AWS

### ISSUE THREAD

**Issue by waf** [bkkhack/hacknights#104]
Learning [Clojure.Spec](http://clojure.org/about/spec), a new feature of Clojure 1.9.

I'll be trying to use it with the AWS API via the [Amazonica](https://github.com/mcohen01/amazonica) library.

**Comment by drawnwren** [comment]
I'm doing the 4Clojure thing over at Orange. Want to start a clojure table?

**Comment by drawnwren** [comment]
How did you end up liking spec? My email is drawnwren@gmail, I'm always interested in talking about/messing with Clojure.

**Comment by waf** [comment]
@DrawnWren Sorry, I missed your last comment! I'm still very beginner with spec, but so far it's scratching my need for static typing. The destructuring support in it is useful too. I'll be playing with it again next hacknight

**Comment by Raulenzes** [comment]
I'm going to do a new project based on AWS and some researching. I can help on AWS stuff.  Maybe we can start this table together :)
