### ISSUE TITLE
Hacking with MeetUp and GoogleAPI

### ISSUE THREAD

**Issue by zshanhui** [bkkhack/hacknights#108]

**Comment by zshanhui** [comment]
Find Tech MeetUp application, jQuery/React frontend.

**Comment by djay** [comment]
can you work out how to meetup users automatically added to a github team? :)

**Comment by zshanhui** [comment]
Not sure I understand that feature. Is this like for RSVP member to be automatically added to the github team. If there's an api for that that, don't see why not.

**Comment by zshanhui** [comment]
meetup integrated, now adding geolocation and more apis.

**Comment by ches** [comment]
Sounds cool, did you publish a project repository?

**Comment by zshanhui** [comment]
Not yet. I'm back in KL for work. Will publish a repo soon when more apis are integrated.
