### ISSUE TITLE
Playing aroung with Neural networks for monitoring cardiac data - DeepHeart

### ISSUE THREAD

**Issue by salinceva** [bkkhack/hacknights#112]
DeepHeart is a neural network for predicting cardiac abnormalities from phonocardiogram (PCG) data. The data provides heart recordings from several patients labeled as normal or abnormal. It is difficult to predict patient health from PCG data because of noise from several sources: talking, breathing, intestinal sounds, etc.

Will try to use TensorFlow to train dataset of wav files and separate signal from noise

**Comment by tao-pr** [comment]
Interesting topic. Are you planning to use frequency-domain features?

**Comment by salinceva** [comment]
hi starcolon Yes my understanding is that the data set is made up of wav files that will be run through FFT filter to convert signal into a frequency domain. There is also a Butterworth filter that needs to be used to reduce noise above 4Hz then transformed to frequency domain. ( separate background sounds such as when patient is breathing talking etc ) 

This is all very new to me and I’m currently stuck at the Tensorflow training vector. would love some help from people more knowledgeable than me.
