### ISSUE TITLE
Try to do some Computer Vision with Tensor Flow

### ISSUE THREAD

**Issue by horngep** [bkkhack/hacknights#113]
I worked on computer vision before, but not so familiar with TF. Perhaps someone who uses TF before will be helpful, but everyone who is interested are more than welcome to join !

**Comment by pairochjulrat** [comment]
Please, count me in.

**Comment by horngep** [comment]
more than welcome krub :D

**Comment by citizen428** [comment]
I'd be interested. Will you attend tonight?

**Comment by horngep** [comment]
I might be able to. What is the time and place this time ?

**Comment by ches** [comment]
@horngep It's 7pm at Oozou, same as last time: http://www.meetup.com/bkkhack/events/231783700/

Some other folks also tried some related experiments recently and might have some learnings to share, cc @aljones15 @salinceva

**Comment by horngep** [comment]
thanks @ches , I should be able to drop in tonight.

**Comment by stankosy** [comment]
Cool! Looking forward to talk more with you about this project tonight! :)

**Comment by horngep** [comment]
@stankosy @ches @citizen428 @aljones15 @salinceva 

Hi guys, really sorry about this, unfortunately I couldn't make it tonight. (Probably wont make future meetups either, since ill be flying back to UK soon)

However, if you guys are interested in Computer Vision in general, I am more than happy to talk about it, either in person or online! (I specifically worked on multiple object tracking before, so will be able to talk a little deeper on that, if any of you guys are interested)

Apology for the inconvenience.
Regards
Ren

**Comment by stankosy** [comment]
Hi Ren,

thank you for the email. Its a pity to hear that, however would be happy to keep in touch with you and talk about AV. 
When do you plan to leave?
If we dont manage to meet before wish you a safe flight! 
You can add me on Fb: stan kosy.

Kind Regards,

Stan Kosyakov

Am 25. August 2016 17:29:54 GMT+07:00, schrieb I-Horng Ren Huang notifications@github.com:
