### ISSUE TITLE
hybrid mobile apps

### ISSUE THREAD

**Issue by jjmax75** [bkkhack/hacknights#117]
looking at React Native and comparing it to Ionic 2

**Comment by jjmax75** [comment]
Got started, environment set up, thanks to @hirosige for the help and advice

**Comment by h-nasu** [comment]
@jjmax I think my github name is @h-nasu.
By the way just for a note, I have posted the things we did to build React Native Android App from Windows or Linux on my blog.
http://www.cyber-th.com/en/running-react-native-app-on-android-from-windows-or-linux/
Hope can help somebody who have similar problem.
