### ISSUE TITLE
Check out Studiolink

### ISSUE THREAD

**Issue by seba10000** [bkkhack/hacknights#119]
https://github.com/Studio-Link-v2/

**Comment by ches** [comment]
Any takeaways from your initial foray? Seems interesting but the site and GitHub projects are light on docs and I don't read German :grin:

**Comment by seba10000** [comment]
Yeah light on the docs..at least i could build and install, but i would need to invest more time to deeper understand it. Thanks for the event,
Sebastian

Am 18. August 2016 07:57:58 MESZ, schrieb Ches Martin notifications@github.com:

> Any takeaways from your initial foray? Seems interesting but the site
> and GitHub projects are light on docs and I don't read German :grin:
> 
> ## 
> 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/bkkhack/hacknights/issues/119#issuecomment-240631057

## 

mobile mail
