### ISSUE TITLE
Expertise: Apache Solr

### ISSUE THREAD

**Issue by arafalov** [bkkhack/hacknights#123]
I am happy to help anybody to understand how Search using the open-source Apache Solr fits into their project/hack.

**Comment by delta-9** [comment]
Hi,  I'm using solr on a lot of projects, would love to have a better understanding of the core mechanisms +1

**Comment by arafalov** [comment]
Perhaps a [Solr Example Reading Group](http://bit.ly/SolrERG) would be something of interest to you. I am running it (virtually) in November.
