### ISSUE TITLE
Ionic 2 map app

### ISSUE THREAD

**Issue by jjmax75** [bkkhack/hacknights#125]
setup an app in Ionic 2 which incorporates geolocation, maps and saving locations to a database

**Comment by jjmax75** [comment]
going to also look at building this with react

**Comment by aifarfa** [comment]
interesting! :smile:
are you gonna use react-ionic or native?

**Comment by jjmax75** [comment]
5555555!
Maybe monkey patch angular 1 mixed with ionic 2 and redux for state
