### ISSUE TITLE
Monopoly Deal - create web game

### ISSUE THREAD

**Issue by claudiopolis** [bkkhack/hacknights#126]
My nephews in another country and I like to play Monopoly Deal. Want to create a simple web version of the game we can play remotely.

**Comment by aljones15** [comment]
that sounds cool what framework are you using?

**Comment by wulab** [comment]
I wish #127 and #129 could work together with this idea.

**Comment by aljones15** [comment]
while giving up haskell practice is annoying I do think that the night needs more collaboration so I'd be more than happy to help. doing it in clojure would be fun too a bit more functional practice and also a project that's a tad less blue sky than my current one.

**Comment by ches** [comment]
I would have bet @waf probably has Closure in mind for #129 even without seeing the linked article 😄 

I think @claudiopolis was telling me he wanted to do Python but I'm not certain.

**Comment by claudiopolis** [comment]
I'm open to doing it anything. I used to code, but I'm practically a n00b again. Sorry couldn't reply sooner. Still have family in town after my wedding.

**Comment by claudiopolis** [comment]
Hi all - need to bail on tonight, but please take it up without me, and/or I will be happy to work on it next time I can attend.
