### ISSUE TITLE
euterpea Synths

### ISSUE THREAD

**Issue by aljones15** [bkkhack/hacknights#127]
Once upon a time I was a musician, now I just program all day. Time to get back on the treadmill. Going to work with Espousa in Haskell to get some functional practice and learn a little about basic synths. exciting. http://www.euterpea.com/

**Comment by aljones15** [comment]
wow sorry about not assigning everything.

**Comment by ches** [comment]
Oh no worries, I just compulsively do it so people can more easily see faces in the Waffle UI, makes it look a bit more personal.
