### ISSUE TITLE
Functional game design with Component-Entity-System

### ISSUE THREAD

**Issue by waf** [bkkhack/hacknights#129]
Learning about Component Entity System method of video game development, with a focus on combining that pattern with functional programming. 

http://www.chris-granger.com/2012/12/11/anatomy-of-a-knockout/

**Comment by ches** [comment]
I'm interested in the topic generally speaking, but haven't touched Closure yet (nor any other Lisp, for quite a few years). And I get distracted a lot anyway, so don't wait for me but I might leer over your shoulder 😊

**Comment by waf** [comment]
I'm not sure what language I'm going to do this in yet. Clojure would be easy (wheee, everything's an untyped map!), but I might choose a statically typed language to make sure I build a coherent system.

**Comment by waf** [comment]
Looks like I'll be doing this in C#
