### ISSUE TITLE
Realtime 4-Player Chess Game

### ISSUE THREAD

**Issue by Joncom** [bkkhack/hacknights#136]

**Comment by Joncom** [comment]
![4 Player Chess](https://upload.wikimedia.org/wikipedia/commons/9/95/Four-handed_chess.png)

**Comment by Joncom** [comment]
Open to suggestions, but perhaps the game could be something like:
- 4 players each direct their internet browser to the game URL
- game URL is hosted by a NodeJS server
- server waits for 4 players before game will commence
- when all 4 players are connected, a count-down displays to each player (3, 2, 1, go!)
- players can move their pieces in real time (no waiting for turns, so think fast)
- when your king is dead, you can no longer play (perhaps all of their pieces disappear from the board, or perhaps they remain to be used as strategic "cover"?)

**Comment by Richard87** [comment]
Haha,  sounds very cool! I have just started exploring Firebase /angular2,  maybe I could help?

Also,  what about different modes (free movement could be the first implementation),  I think maybe 2 turns could be fun too (bottom+right can move one piece at the same time (first move wins),  then second round top+left can move? 😀

**Comment by Joncom** [comment]
Sound cool, @Richard87!

**Comment by Richard87** [comment]
Are you coming tonight @Joncom ?

**Comment by Joncom** [comment]
Hey @Richard87. Yeah, I'm here right now, haha...

**Comment by Joncom** [comment]
@Richard87, are you here tonight?

**Comment by mengstr** [comment]
I like this idea, love to try it out whenever it is in playable shape...

**Comment by Richard87** [comment]
haha, it still needs some work ;)

**Comment by Joncom** [comment]
Haha, true...
