### ISSUE TITLE
Scala: Cats and Shapeless lessons from scala-exercises.org

### ISSUE THREAD

**Issue by ches** [bkkhack/hacknights#139]
If anyone is interested in some intermediate-to-advanced Scala learning, I might work through some of the exercises on https://www.scala-exercises.org/ for libraries like Cats or Shapeless, or offer pointers if you're a Scala beginner and want to do the standard library lessons instead. You can do these without even needing to set up any local development environment on your computer.

This lesson site is pretty new and the lessons are sometimes still sparse, so we can do deeper research on the topics together. I'm pretty well-acquainted with Scala but not an expert on these more advanced pure-functional uses.

Cats covers a lot of similar territory to common Haskell typeclass abstractions, so if you have a Haskell background and are learning Scala you will probably find that it's familiar territory.

**Comment by aljones15** [comment]
I actually could use some Scala lessons for my figaro book so I might consider doing a few of these seeing as how just css for 4 hours... to much css... to much design stuff.

**Comment by ches** [comment]
I'm curious to hear how the standard lib section goes for you, haven't done that one—the ones I've done are definitely still work-in-progress but the format and not needing to set up a dev environment ahead of time is promising. It's a cool open source foundation for people to contribute to.
