### ISSUE TITLE
Blockchain receive payment

### ISSUE THREAD

**Issue by sthapaun** [bkkhack/hacknights#140]

**Comment by sthapaun** [comment]
Receive bitcoins with blockchain api (python)
play with this demo
https://github.com/blockchain/receive-payments-demos

**Comment by wulab** [comment]
@sthapaun Are you joining BKK/Hack event next week?

**Comment by sthapaun** [comment]
Sure!

**Comment by aljones15** [comment]
is there going to be a block chain event this week? I need money so working with digital money might make me feel better.

**Comment by ches** [comment]
Sorry I closed this, I didn't notice everyone's comments carrying on to today's event. Of course feel free to re-open if you all want to continue 😃
