### ISSUE TITLE
Hook up Babel/transpiler to an existing NPM package

### ISSUE THREAD

**Issue by cbrunnkvist** [bkkhack/hacknights#143]

**Comment by cbrunnkvist** [comment]
I haven't used Babel that much but I'd like to see how much work it is to wire it up to an ES6-only module to make it portable across various browser / node runtimes.

**Comment by aljones15** [comment]
shouldn't be to hard actually in fact babel trans-piling is the norm with React and several other popular npm libraries.

**Comment by cbrunnkvist** [comment]
That was what I'm thinking :) there's also a (mocha) test suite and it would be sweet to have it run "everywhere" too

**Comment by cbrunnkvist** [comment]
Finished ... the key was to :
1. move all files (tests too) into "src" 
2. make the npm prepublish step run babel and output into "dist", 
3. keep common files such as data, readme and package.json in the root and set entry point to "dist/index.js" 
4. add "src" to .npmignore and "dist" to .gitignore 

and a few small tweaks to get around missing `this` object in arrow functions.

**Comment by cbrunnkvist** [comment]
HOW DO YOU "CLOSE" A WAFFLE?
