### ISSUE TITLE
Stackbased CPU Simulator & Experimental Programming Languages

### ISSUE THREAD

**Issue by scherrey** [bkkhack/hacknights#144]
An experimental simulator project to explore the usage of stack-based computing for extensible statically typed programming languages. Written in Python3 (for now) ultimately hope to move it to an FPGA with a custom stack-based CPU in the future.

Open Source found here: https://git.proteus-tech.com/scherrey/rolestack

**Comment by aljones15** [comment]
wooo that is cool.
