### ISSUE TITLE
React Redux Firebase CRUD

### ISSUE THREAD

**Issue by JesseSoldat** [bkkhack/hacknights#146]
making a CRUD app with React Redux and Firebase. Looking for someone with Redux experience.

**Comment by aljones15** [comment]
what syntax are you using? I've built 3 redux apps now and am considering using it with my react native demo app. Are you using the official bindings from here: https://github.com/reactjs/react-redux?
it's quite easy if so make Provider your top level jsx element then just implement the interfaces for mapStateToProps and the other one and redux will automatically update the props for the jsx element whenever they change. Also state.whatever = new data then Object.assign({}, state) is the easy way to cause an update to trigger in the reducer.

**Comment by aljones15** [comment]
- install android dev tools
- get react native demo app running in emu
- replicate ios views in android
- get redux and bindings working in react native
