### ISSUE TITLE
TDD on Django/Django REST, Docker with pytest: Project Android Chit-Chat App

### ISSUE THREAD

**Issue by elcolie** [bkkhack/hacknights#147]

**Comment by elcolie** [comment]
Platform : GNU/Linux Debian on Docker
Backend = Django/Django REST
Mobile = Android 4
Goal = Practice pytest not only data manipulation, but also authentication&permission, I/O, Mock object
Bonus = Have hard case experience for example meta class and APscheduler

**Comment by montionugera** [comment]
Hi I am Django / Docker guy who comments in meet up.

**Comment by elcolie** [comment]
Hi :D

**Comment by elcolie** [comment]
@montionugera Hi I am in the meeting, but got emergency call from my customer. Hope I can find you next time. This time if I can finish my incident in time I would join Djay project. Sorry sorry
