### ISSUE TITLE
Learning Python

### ISSUE THREAD

**Issue by shanetorr** [bkkhack/hacknights#152]
Learning Python from scratch

**Comment by wannadrunk** [comment]
Would like to join this tonight.

**Comment by impco** [comment]
Interested. Is there a senior dev helping the newbs to learn?

**Comment by shanetorr** [comment]
I hope we can find someone there - I don't know Python myself - just interested to learn

**Comment by djay** [comment]
The idea is to go there prepared to learn yourself via a online course or similar and if someone happens to want to help then great. There will certainly be senior python developers there including myself so if there are specific question you want to ask then please come and find us
