### ISSUE TITLE
Mobile DarkSky Weather App with Xamarin/C#

### ISSUE THREAD

**Issue by timchaffee** [bkkhack/hacknights#158]
Build a simple mobile app for iOS and Android. Let's use the DarkSky API to build a simple weather app for iOS and Android.

https://darksky.net/dev/login?next=/account

So far I have converted this https://github.com/jcheng31/DarkSkyApi to a .Net Standard library so we can build with .Net Core.

**Comment by rawinng** [comment]
:D Take this on

**Comment by timchaffee** [comment]
I might be a little late tonight

**Comment by timchaffee** [comment]
I am here at one of the white tables, black and white checkered shirt ( a little wet :) )

**Comment by timchaffee** [comment]
.Net Core standard library compiles and tests passing. Time to try and get it working on Mobile.
