### ISSUE TITLE
update current meetup details and venues in Thai

### ISSUE THREAD

**Issue by aifarfa** [bkkhack/hacknights#161]
How Hack night works:

> 1. Please ensure you RSVP @ https://www.meetup.com/bkkhack/
> 
> 2. Think up something you want to do or learn. Come prepared. If you are new to computing, sign up for an online course. Discuss topic ideas on our Gitter chat channel.
> 
> 3. Turn up, write a name badge with your name and topic, find a table and hack away. Others doing similar stuff will come and sit next to you.  Don't forget your laptop, to leave your day at work and most of all have fun.

updated Thai version about meetup venues
-----

จะเขียนภาษาไหน ระดับใดก็ได้ มีกฎข้อเดียวคือคุณต้องเอาเครื่องมาเอง 

**NOTE** *ในเดือนนี้เราไม่มี Pizza คุณสามารถนำอาหารมาทานเองในงานได้ตามสะดวก*

ก่อนเข้างาน อย่าลืม:

1. กด RSVP (Are you going: Yes) และบอก username GitHub ของคุณ

2. คิดหัวข้อไอเดีย ที่คุณสนใจ เตรียมตัวให้พร้อมก่อน ถ้าหากคุณยังใหม่กับโปรแกรมคอมพิวเตอร์ [ลองสมัครคอร์สออนไลน์](https://github.com/bkkhack/resources/wiki) ดูครับ พูดคุยแลกเปลี่ยนไอเดียกันได้ที่ [Gitter channel](https://gitter.im/bkkhack/hacknights)

3. เมื่อมาถึงในงาน เขียนป้ายชื่อ หาโต๊ะนั่งตามหัวข้อ topic ที่เลือก แล้วเริ่ม hack กันได้เลย สมาชิกคนอื่นๆ ที่สนใจเรื่องเดียวกันจะมานั่งรวมกลุ่มโต๊ะเดียวกับคุณ อย่าลืมเอา laptop มาด้วย ขอให้สนุกกับงานครับ

*พบกันที่ออฟฟิศ Kaidee เวลา 1 ทุ่ม (แลกบัตรได้ที่ประชาสัมพันธ์ไปออฟฟิศขายดีชั้น 14fl.)

ไม่ว่าคุณอยากจะเขียนภาษาอะไร Python, Ruby, JavaScript, Scala, PHP, Prolog คุณมาได้เลย อยากทำ Arduino ก็ขนมาได้ ถ้าอยากหาทีมสำหรับทำโปรเจค open source หรือหาคนช่วยโปรเจคงานอดิเรกของคุณจัดมาเลย!

ถ้าคุณมีกลุ่มคนเขียนโค้ดในกรุงเทพฯก็ชวนชุมชนของคุณมาได้เลย งานนี้เป็นงานที่ดีที่จะให้สมาชิกในชุมชนของคุณช่วยเหลือกัน

**Comment by aixasz** [comment]
NOTE ในเดือนนี้เราไม่มี Pizza คุณสามารถนำอาหารมาทานเองในงานได้ตามสะดวก

Kaidee จะเป็นเจ้าภาพให้เราอีกครั้งซึ่งของออฟฟิศของเขามีพื้นที่เพียงพอสำหรับ hack และมี internet ที่เร็วพอ.

How Hack night works:

1. กด RSVP (Are you going: Yes) และบอก username GitHub ของคุณ

2. นึกถึงสิ่งที่อยากทำหรืออยากเรียนเตรียมไว้  สำหรับมือใหม่สามารถลงทะเบียนเพื่อรับ [online couse](https://github.com/bkkhack/resources/wiki) และแลกเปลี่ยนความคิดเห็นและหัวข้อต่างๆที่ [Gitter chat channel](https://gitter.im/bkkhack/hacknights).

3. เมื่อมาถึงแล้ว เขียนป้ายด้วยชื่อของคุณและหัวข้อไว้ มองหาโต๊ะว่างแล้วเริ่ม hack ได้ คนที่ทำในเรื่องที่คล้ายๆ กันจะมานั่งถัดจากคุณ โปรดอย่าลืมนำโน๊ตบุ๊คของคุณ ที่จะปลดปล่อยทั้งวันของคุณจากที่ทำงาน และมาสนุกกับทุกคน

**Comment by djay** [comment]
Thanks @aixasz
