### ISSUE TITLE
3D object tracking

### ISSUE THREAD

**Issue by tao-pr** [bkkhack/hacknights#162]
Just a fun project using OpenCV (C++) to capture and track objects via camera. 

Continued from last week. Here is the repo: https://github.com/starcolon/3d-motion-tracking :)

Just for fun & learning

**Comment by elcolie** [comment]
So what is your topic anyway. Motion or Object tracking?

**Comment by mister51213** [comment]
Sounds fascinating. I'm also a C++ programmer doing a lot of 2D and 3D spacial simulation. Currently working on a physics engine. Would love to talk more!

**Comment by tao-pr** [comment]
@mister51213 Nice. What kind of spatial 2d/3d simulation are you working on these days? Interesting
