### ISSUE TITLE
Google Polymer 2.0 and Web Components

### ISSUE THREAD

**Issue by waf** [bkkhack/hacknights#165]
I'm learning [Google Polymer](https://www.polymer-project.org/) from the beginning. It looks like 2.0 is almost released, so I'm going to be learning that instead of 1.0.

I'll be working through this page: https://www.polymer-project.org/2.0/toolbox/app-layout

My sample app will be a Thai/English vocabulary mobile app.

**Comment by aljones15** [comment]
Looks cool
