### ISSUE TITLE
Play with Firebase

### ISSUE THREAD

**Issue by AlexStansfield** [bkkhack/hacknights#168]
Looking to learn something new. Was going to try and create a really simple blogging platform using firebase and angularjs

**Comment by TongWR** [comment]
Anyone interested in playing with Firebase in the coming meetup?

**Comment by nadam** [comment]
Yup! I'm looking into Firebase and React Native.

**Comment by aljones15** [comment]
Jesse is really into firebase. not sure if he will be there.

**Comment by TongWR** [comment]
Awesome! I wanna try Firebase with D3.js so we have common theme here. See you all tomorrow :)

**Comment by ches** [comment]
Calling @JesseSoldat in case he is going to be present this month.

**Comment by JesseSoldat** [comment]
Sounds like fun. I will be there

**Comment by TongWR** [comment]
For those who are new, you might find this Firebase Web Codelab (building chat app client) helpful: https://codelabs.developers.google.com/codelabs/firebase-web/#0

**Comment by steve1rm** [comment]
I would be interested to use Firebase with Android to do push notifications. If anyone is interested. Maybe create a peer-to-peer chat app.
