### ISSUE TITLE
Learn Julia as a n00b

### ISSUE THREAD

**Issue by tao-pr** [bkkhack/hacknights#169]
First time hands-on coding in Julia (preferrably Julia notebook). Completely newbie who knows nothing about Julia. Just for fun.

**Comment by aljones15** [comment]
https://www.manning.com/books/julia-in-action

I actually have this meap. It isn't finished yet if you want a pdf I could send the first few chapters.

**Comment by tao-pr** [comment]
That's nice! As a quick start, I'm looking at:
https://learnxinyminutes.com/docs/julia/

**Comment by aljones15** [comment]
Leave your email I an send a pdf with basic machine learning algorithims to implement. Might do Julia depends.

**Comment by tao-pr** [comment]
pataoengineer@gmail.com 
Great thanks. I just initiated a quick notebook at https://github.com/starcolon/data-with-julia Will try something cool tmr
