### ISSUE TITLE
Open Source Bare metal to containers for dynamic scaling

### ISSUE THREAD

**Issue by linusidom** [bkkhack/hacknights#172]
I want to be able to take a Bare Metal server or Blade Chassis, Kickstart the boxes, add them to a VM cluster, add containers to each VM, and offer it as a service.  All of this from bare metal to service should be done without any human operation other than racking/stacking and VM designation.

High level
MAC address of bare metal delivered before shipment
MAC address assigned and Virtual MAC's assigned and designated for functionality
Startup scripts and base functionality deployed on VM's
Public Front end service picks up and increases capacity on demand.

When not being used, bare metal should power down.

**Comment by graffic** [comment]
Don't know which tools you plan to use, but take a look to: https://theforeman.org

**Comment by linusidom** [comment]
didn't have any in mind but this is an awesome start.  Thanks! :)

**Comment by udomsak** [comment]
@linusidom actually  you can use many of  bare-metal provision tool , chef, cobbler , etc. . However I interest this too.  my goal how to  deploy / manage ARM base bare-metal CPU  ( think about  DC cluster of ARM  not container)

**Comment by ches** [comment]
[Crowbar][1] is another project worth looking at in this space. Once a Dell project, now supported by SUSE. I don't think it necessarily has to be specific to OpenStack, at least it wasn't originally.

[1]: http://crowbar.github.io/
