### ISSUE TITLE
Solving a Sudoku with AI

### ISSUE THREAD

**Issue by kwarodom** [bkkhack/hacknights#173]
As i've enrolled in the Udacity Artificial Intelligence nanodegree, the first assignment is to come up with an AI agent that can automatically solving puzzle by itself using constrain propagation and search algorithm.

**Comment by aljones15** [comment]
congrads! so jealous =)

**Comment by linusidom** [comment]
This sounds cool!  i want to join :)

**Comment by kwarodom** [comment]
Interesting article took read on Elon Musk plan too keep us updated with AI technologies

https://techcrunch.com/2017/01/25/elon-musk-could-soon-share-more-on-his-plan-to-help-humans-keep-up-with-ai/

**Comment by kwarodom** [comment]
This 9x9 diagonal Sudoku >> diag_sudoku_grid = '2.............62....1....7...6..8...3...9...7...6..4...4....8....52.............3' (' . ' represents no value in that box) <<  has been solved :). The techniques being used here as constraint propagation are (1) elimination, (2) only choice, (3) naked twins, (4) Depth-First Search

Please see : https://www.youtube.com/watch?v=kKebNoU-A_g

You can check out the following repo to learn more or replicate the Sudoku problem: https://github.com/kwarodom/AIND-Sudoku

**Comment by pmdscully** [comment]
Fun problem, can also be solved with an algorithm implementing (1) certainty and (2) probabilistic (greedy) step-wise search with backtrack. 

Could be interesting to compare runtime performance between solutions too. 

I hope I can catch you at the next meetup.

**Comment by kwarodom** [comment]
Hi pmdscully, now i'm at bkk hack night. Let's catch up if you still interested :).
