### ISSUE TITLE
Use JsVerify to test react components

### ISSUE THREAD

**Issue by aljones15** [bkkhack/hacknights#176]
Property based testing sounds cool so going to sit down and try to get some fluency with JsVerify constructing props for react components etc.

**Comment by cbrunnkvist** [comment]
Intriguing. I just read the entire page http://jsverify.github.io/#jsverify and I don't understand at all how it is supposed to work. 

Perhaps a PR for the README would be my first contrib ;-)

**Comment by aljones15** [comment]
yeah property based testing frameworks are terribly obfuscated I've found, but basically you specify the type for the paramaters to a function and it then produces over 100 randomized unit tests for the function.
