### ISSUE TITLE
Build an Anki database of Thai vocabulary using Python

### ISSUE THREAD

**Issue by waf** [bkkhack/hacknights#177]
[Anki](https://en.wikipedia.org/wiki/Anki_(software)) is a free/open source app to aid memorization, using flash cards and [spaced repetition](https://en.wikipedia.org/wiki/Spaced_repetition).

I'm building several Anki decks full of Thai/English vocabulary. I have a large JSON file, and I'll be using Python to transform it into an Anki APKG database. The database is SQLite, but I'll be using an Anki API to actually build it.

I haven't used Python in a while, so I'll also be re-learning python as I go. 👀

**Comment by ches** [comment]
What's the source of your JSON data? I ought to brush off Anki and start studying with it again, motivation fell off largely because of… getting data into it. So this could be a practical project :smile:

**Comment by waf** [comment]
The best word list I've been able to find is [SEAlang's Thai website](http://sealang.net/thai/vocabulary/).

I converted that site to [a huge JSON file](https://raw.githubusercontent.com/waf/flash-cards/master/data/cards.sealang.json), and next I'll need to figure out how to structure it into Anki decks in a non-overwhelming way.

Anki's desktop client is written in python, so I'm planning to import its python modules and use them to script the DB creation. Some "guy on the internet" posted this code that looks promising: http://superuser.com/a/1127023

**Comment by waf** [comment]
Thanks to [ibotdotout](https://github.com/ibotdotout) for helping with this! We finished it. The [source is here](https://github.com/waf/anki-json) and a completed APKG file (pending some nicer styling) that can be imported into Anki is here: https://github.com/waf/anki-json/blob/master/dist/thai.apkg?raw=true
