### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by babedev** [bkkhack/hacknights#184]
Thinking about Kotlin full stack development

**Comment by babedev** [comment]
Thinking about Kotlin full stack development

**Comment by ches** [comment]
We don't have a Kotlin label yet so forgive me for tagging this with some JVM cousins in the meantime, might help a few people notice it who aren't familiar with Kotlin yet :blush:

**Comment by bhargavg** [comment]
This sounds like fun. I'm an iOS dev, doing mostly Swift. Kotlin seems to be more like Swift (or the other way around?) and I want to try out Android development with Kotlin.
Can I join this group?
