### ISSUE TITLE
React and Node Polling App

### ISSUE THREAD

**Issue by jjmax75** [bkkhack/hacknights#191]
Use create-react-app and Node with Express for API

**Comment by Jpang93** [comment]
Hi, I am fresh graduate new to bangkok. Can i join you?

**Comment by elcolie** [comment]
@Jpang93 Yes, you can

**Comment by Jpang93** [comment]
Sorry, i was in emergency yesterday. So the next time meeting will be the next month? have you guys meet up during free time? i am staying near rama 9

**Comment by philipphalder** [comment]
are u working on that tomorrow too?

**Comment by jjmax75** [comment]
Hi @philipphalder I won't be there tonight but I'm still working on this in spare time.

I've built some Node API points for users and polls, setup very basic Auth0 authentication on an untouched create-react-app frontend.

The repo I'm using is https://github.com/jjmax75/votingApp2
I'm basing the app on this project from Free Code Camp - https://www.freecodecamp.com/challenges/build-a-voting-app

I have a Trello board setup to track what needs to be done, currently that's full on the backlog side :)

Let me know if you're interested in working on this and we can put our heads together. I want to build it up a bit and then host on DigitalOcean using Dokku

**Comment by aljones15** [comment]
Have you considered using Graph QL and Relay with this? I'm working on a simple Relay app.
https://learngraphql.com/
https://www.learnrelay.org/

**Comment by jjmax75** [comment]
I have been thinking about using Graph QL alright, not on this project now as I just want to get it done now but it's definitely something I'm interested in.

I hadn't looked at Realy yet, using Redux in work and really like it, so would definitely be open to using it.

What's your app?

**Comment by aljones15** [comment]
Relay is based off of Flux, but simplified taken the success of Redux over Flux. Not entirely sure on Relay TBH the abstraction doesn't seem to be that useful so far could just a generic graphQL query over Relay in most cases. my app is this one: https://github.com/aljones15/RelayMapToDo

I highly suggest the learn graph ql website though it really drives home how useful Graph QL can be when building an api.

**Comment by jjmax75** [comment]
Nice one :) I like the Maps angle on the Todo app

I know what you're saying about the abstraction, same in Redux, I'm touching 5 or 6 files to get a new set of data into the store, but having said that I do still like the way it works and the Dev tools are amazing.

Maybe next time I'm at hacknight we can compare the different approaches in the apps.

**Comment by aljones15** [comment]
it's a little different,. You might actually try making a file that returns an object with the Action type and payload filled out and then you could just pass that to the dispatcher in connect although you probably already did that. Yeah Redux is getting complex and React are getting a little to complicated these days. Relay requires you write fragments and query functions and then a route object which all somehow interact. Hopefully I will know how sometime tonight =)

**Comment by jjmax75** [comment]
😁 good luck with it
