### ISSUE TITLE
Self-learning Doom Bot

### ISSUE THREAD

**Issue by tao-pr** [bkkhack/hacknights#193]
Implement a reinforcement-learning algo for a classic Doom bot to find best strategies to maximise the score! 

I made a repo here : https://github.com/starcolon/classic-doom-bot 
The simple Q-Learning algo has been implemented, up and running over Jupyter Notebook. 

I'll find another more suitable algo to imeplement and test the bot. Just for fun!

**Comment by aljones15** [comment]
this sounds really cool. let me know on slack if this works! would love to look at the code.

**Comment by tao-pr** [comment]
@aljones15 definitely!

**Comment by elcolie** [comment]
Then let's create bot and fight

**Comment by aljones15** [comment]
@elcolie  that's actually a cool idea. Doom has a lan multiplayer mode so it would be cool to see learning algorithims against learning algorithims deatth match. Might be easier in source 2 though.

**Comment by tao-pr** [comment]
Not so much progress made tonight  :hushed: 
I drafted a structure for [Temporal Difference learning algo](https://web.stanford.edu/group/pdplab/pdphandbook/handbookch10.html) but still in the middle of trying to understand how the algo works before rushing into implementation. 

I also have a baseline & simpler strategy implemented based on Q-learning here in [master branch](https://github.com/starcolon/classic-doom-bot). I trained it for like 600 rounds and it knows how move and shoot, but still isn't smart enough  :smile:

**Comment by aljones15** [comment]
Thanks for the update hope to understand your project soon. :)

**Comment by aljones15** [comment]
https://keon.io/deep-q-learning/  If you didn't see this one its a Q learning in Keras tutorial.

**Comment by tao-pr** [comment]
@aljones15 Nice article. Deep Reinforcement Learning sounds interesting to try out at some point, perhaps after Temporal Difference. Wanna compare Deep QL against basic QL too.

**Comment by elcolie** [comment]
Are you ready to show?
