### ISSUE TITLE
Look at react.js and react-native to create multiplatform mobile app

### ISSUE THREAD

**Issue by delta-9** [bkkhack/hacknights#2]
I'm currently developping a real-world mobile app for android with react native. I would like to share what I've already learn also if people are interested to learn this I will be happy to help.

I have already use react.js for a personal use but I'm quiet new to this whole (and wild) ecosystem. 

Courses :
https://news.ycombinator.com/item?id=11204481
https://github.com/reactjs/react-router-tutorial

Some materials :
https://github.com/bartonhammond/snowflake
https://github.com/enaqx/awesome-react#react-native-awesome-components

Discord : http://join.reactiflux.com

Setup an environment for ubuntu :
https://delta9.link/blog/setup-a-react-native-development-environment-on-ubuntu

**Comment by csymons** [comment]
i was thinking of playing with react native (or just react.js) on the 24th too!

**Comment by delta-9** [comment]
Cool, let's play together ;)

**Comment by jjmax75** [comment]
I'm interested too. Learning React now with a view towards getting into React Native, see you on the 24th

**Comment by delta-9** [comment]
Too bad... I just realised it was on thursday (not tuesday)... I'm so french ... Its the second time that I can't attend.. I'm so frustrated, damn calendar.. Let the issue open for you guys. Sorry that I can't be there...

**Comment by jjmax75** [comment]
too bad man, we'll try and meetup at another time in the future,can you add me as an assignee/contributor to this topic and I'll manage it on the night if that's OK with you?

**Comment by delta-9** [comment]
Yeah. I can't add you @jjmax75, you may not been added to the github group, ask an organisator for that. I added csymons as the assignee.

**Comment by jjmax75** [comment]
thanks, I'll get added now

**Comment by delta-9** [comment]
@jjmax75 when you will be in the group, you could assign the issue to yourself

**Comment by aifarfa** [comment]
anyone still gonna do this today?

**Comment by jjmax75** [comment]
i'm here on the Grape table

**Comment by jjmax75** [comment]
GitHub repo at - https://github.com/aifarfa/todomvc-react
Slack channel setup on ThailandDevs, could only add private so just send a request to join if interested
App structure designed - draft, may need some changing when data comes into play
Going to continue work on project, code review, learn about unit testing the app

**Comment by ches** [comment]
Awesome, seems like you guys made some great progress. If you continue on it next time please do either re-open this or create a new card with the April 28th milestone! Would be great to summarize what resources you followed so far and include link to the repo, so others could catch up with you and join in later.
