### ISSUE TITLE
Om Tutorials and maybe some Haskell at the end

### ISSUE THREAD

**Issue by aljones15** [bkkhack/hacknights#207]
https://github.com/aljones15/SimplePathFinding
Haskell Search Algorithms Project:
1. see if I can get nix os' ncurses to work with my stack project 
2. if possible continue working on Breadth First Search
3. Look into a higher order function that is giving some type errors

https://github.com/aljones15/clojure-conway
it's possible I won't be able to solve the ncurses issue so instead:
1. look at clojure conway game of life 
2. try again to implement an r/fold version of it (pmap works just fine)
3. work on my om home page.
4. hmm what can this figwheel thing do.
5. find a style library that uses flex box for my om page

**Comment by tao-pr** [comment]
Oh, A* and Dijkstra on Haskell must be much fun ...

**Comment by aljones15** [comment]
didn't get actually get around to it still haven't figured out what missing ncurses libs are causing the build issue in nix
