### ISSUE TITLE
Exploring Google Vision API

### ISSUE THREAD

**Issue by sthapaun** [bkkhack/hacknights#28]

**Comment by Robert-Ernst** [comment]
Say when you arrived. Your thing sounds interesting

**Comment by ches** [comment]
https://cloud.google.com/vision/

What did you think about using the API to do? It might be interesting to compare ideas and learning with @mishari on #49.

**Comment by sthapaun** [comment]
It can detect things so much deeper than I thought. What I interest most right now is it can also detect people emotion. Next I will create a simple app to playing around with it using golang and google closure javascript library and share it on docker hub.

**Comment by dkatamari** [comment]
I would be very keen on joining in on this as well...

**Comment by prideloki** [comment]
I would like to join this :)
