### ISSUE TITLE
Make Day Tracker with css and js   http://paulapivat.github.io/project5/

### ISSUE THREAD

**Issue by PaulApivat** [bkkhack/hacknights#33]

**Comment by jjmax75** [comment]
http://stackoverflow.com/questions/31000885/align-an-element-to-bottom-with-flexbox

**Comment by jjmax75** [comment]
http://vanilla-js.com/ :)

**Comment by PaulApivat** [comment]
Thank you John!

**Comment by ches** [comment]
Like a calendar/planner, or journal of what you did, or something like that? How'd it go so far?

**Comment by PaulApivat** [comment]
Here's the simple day tracker :)  While the js was fairly easy to set-up, my big learn was around implementing a switch function within jquery to add and remove classes. 

 http://paulapivat.github.io/project5/
