### ISSUE TITLE
"Tell a Joke" Twilio project

### ISSUE THREAD

**Issue by consti** [bkkhack/hacknights#35]
Create a Twilio project that tells a new joke every day when you call or text the number.

**Update**: It's done! Give it a call here: +1 559-422-6100
The repository is located here: https://github.com/consti/joker

**Comment by ches** [comment]
Success! Dial +1-559-422-6100 :smile:

https://github.com/consti/joker

**Comment by consti** [comment]
I've also created [oozou-cli](https://github.com/oozou/oozou-cli) - although that's probably a little too oozou specific ;)
