### ISSUE TITLE
Create a Hangman game app

### ISSUE THREAD

**Issue by rajul** [bkkhack/hacknights#38]
I have been wanting to get started with Kivy for a long time. Will be trying my hands on it during this Hack Night, trying to develop an app using it.  Anyone is welcome to join.

**Comment by songsuke** [comment]
Hey Rajul !, check out my first Hangman version on Github !!

https://github.com/songsuke/hangman

**Comment by ches** [comment]
For anyone reading, [Kivy](https://kivy.org/) is a Python library for creating cross-platform UIs capable of using native features. Looks cool, would be curious to hear if you got started with it.

Check out @songsuke's #42 for the Ruby on Rails Hangman version :smile:  It would be interesting if you could share test specifications for core game logic between the two versions, like maybe write down an outline of tests together and then implement them in both Python and Ruby.
