### ISSUE TITLE
Make bots for a minimal MOG card game.

### ISSUE THREAD

**Issue by djay** [bkkhack/hacknights#4]
Falling is an a creative commons hugely fun real time card game of 4-8 players. Over 15 years ago I had fun turning it into an multiplayer web app as my first every web app. I lost the code but I recreated it here
http://54.254.172.52/Plone

_but_ it's works much better with 6-7 players. I want your help to help those who have no friends and want to play by themselves. Suitable for beginners to advanced:
- learn the game
- write a simple python function that takes a game board and returns a move.

A board is 

```
dict(next=(player_pos,_stack_index), players=[dict(name="fred", held="split", rider="extra_skip", cards=[["skip","grab"],["hit"]]),...])
```

and return a move of a list of plays. You get 2 plays per deal.

```
stack_index = 0
player_pos = 1
return [('pickup',stack_index), ('play', player_pos)]
```

I will work out how to let anyone interested write their python online and play them against each other.

If you are interested to join at the hacknight then comment below.

**Comment by wulab** [comment]
Count me in :)

**Comment by vrybas** [comment]
Joining

**Comment by wulab** [comment]
Initial implementation in Python:
https://github.com/wulab/falling

Needs a lot of guidances from @djay

**Comment by djay** [comment]
I fixed the bug which prevented you from starting a game on http://54.254.172.52/Plone/game. Should work now. 
The create bots stuff should work but I doesn't give you helpful errors if your code has bugs

**Comment by djay** [comment]
@wulab interesting code. Very OO. Very java looking. But where is the game logic? 
Why not have a try making a bot first?

**Comment by wulab** [comment]
@djay It is a still a WIP. Just get to a card dealing part. I wanted to make a bot but the server was not working yesterday.

**Comment by bkktimber** [comment]
Python newbie, want some hand-on experience. I will try my best.
