### ISSUE TITLE
Create Hangman game by Ruby on Rails

### ISSUE THREAD

**Issue by songsuke** [bkkhack/hacknights#42]

**Comment by songsuke** [comment]
https://github.com/songsuke/hangman

**Comment by songsuke** [comment]
Check out my stupid first version !

**Comment by djay** [comment]
No live server I can play?

**Comment by songsuke** [comment]
It needs improvement. I'll let you know when it's ready. Now it's just a prototype, also it's too embarrassing to show. Even the code sucks lol

**Comment by songsuke** [comment]
here --> I'm using for staging http://hangman-bkk-hacknight.herokuapp.com

**Comment by ches** [comment]
Cool :sunglasses:

Maybe you can add the link to http://hangman-bkk-hacknight.herokuapp.com/ in the GitHub project description/website at the top of the repo page.

Will be fun to see if you add some more interactive feedback and render a hangman as the user runs out of guesses :smile:

**Comment by songsuke** [comment]
We have plans on implementation. Maybe interaction between two users.
