### ISSUE TITLE
[BSD] Learn the basics of GameMaker

### ISSUE THREAD

**Issue by hunterwilliams** [bkkhack/hacknights#5]
- We'll use http://www.yoyogames.com/gamemaker so please install it before. The free version is sufficient
- I'll cover making pong or a basic platformer. Basically the start of programming with GameMaker
- If you don't know how to program at all it's fine! If you do you'll just be able to do more!

**Comment by ches** [comment]
Thanks for posting!

Have some more brief info what this is about? I assume it's http://www.yoyogames.com/gamemaker – what aspects can/would you cover? Suggest installing the tool in advance if possible, free version sufficient?

**Comment by hunterwilliams** [comment]
We'll either do a basic platformer or pong depending on people's comfort levels. The free version is entirely sufficient. Also I totally suggest getting it before then

**Comment by scorpiogit** [comment]
Am interested, but probably another evening, if you are around. I have been teaching kids to make games, including Pong, using Scratch, for years but have never used Gamemaker.
