### ISSUE TITLE
Line Hackathon Team Lineup

### ISSUE THREAD

**Issue by Robert-Ernst** [bkkhack/hacknights#53]
I would be interested to attend, but a team is required. If others would like to attend to, we could try to make up a BkkHack team.

Whoever is interested, can assign himself to this card. 

http://hack.lineapp.me/

**Comment by aifarfa** [comment]
count me in :)

**Comment by jjmax75** [comment]
I'm interested if you need another person

**Comment by rajul** [comment]
I am interested too if you still got a slot left!! :)

**Comment by Robert-Ernst** [comment]
@rajul @aifarfa Do you come over to the apple table? Then we can brainstorm together. :)

**Comment by Robert-Ernst** [comment]
We've built a team and want to participate at the Line Hack.
We created our repo at 
https://github.com/bkkhack/LineHack

**Comment by Robert-Ernst** [comment]
Almost finished the proposal.
Still a team of 4 members :)

**Comment by Robert-Ernst** [comment]
Dear Vision Quest,

Thank you for submitting your Terminus Meeting Bot proposal for LINE HACK.

Due to the sheer number of proposals we received from potential participants, we were unable to shortlist your project to come hack with us at LINE HACK 2016. There were several great ideas submitted, much more than we could take in (we received well over 100, but are only able to take in 12). In the end, we had to carefully weigh proposals in terms of idea/category diversity, proposal quality, team readiness, and overall fit with our business direction to arrive at our final list.

The good news is that your potential partnership opportunity with LINE Thailand does not end with LINE HACK. We may be reaching out some teams to explore further opportunities where we could work together, so stay tuned!

Best regards

Ariya Banomyong (Bi)
Managing Director, LINE Thailand
