### ISSUE TITLE
Statically-typed Lisp in C#

### ISSUE THREAD

**Issue by waf** [bkkhack/hacknights#54]
I'm building a programming language for the .NET CLR, using the [Roslyn compiler platform](https://github.com/dotnet/roslyn). It's statically-typed with [Lisp](https://en.wikipedia.org/wiki/Lisp_%28programming_language%29) syntax. I'm happy to have people help or just talk about it. I'm "taking inspiration" (i.e. shamelessly stealing) syntax from Clojure.

https://github.com/waf/Donatello

**Comment by seancomeau** [comment]
I'm interested in this.

**Comment by waf** [comment]
I've updated the description with a [GitHub link](https://github.com/waf/DotNetLisp).

**Comment by waf** [comment]
Did some great pair programming with @seancomeau. Implemented variable assignment, booleans, and if-else statements!

**Comment by waf** [comment]
Reopening this, as I'll still be working on it next bkkhack. Here's my progress so far:

What's done:
- Beginning [ANTLR4](http://www.antlr.org/) grammar and generated lexing/parsing code.
- REPL (read eval print loop)
- Function definition and invocation
- Variable definition and usage
- Lambda expressions
- Basic types: 
  - Referring to existing CLR types
  - Literal syntax for immutable collections:
    - Arrays `[1 2 3]`
    - Sets `|1 2 3|`
    - Dictionaries `{"a" 5 "b" 3}`
- Calling .NET SDK methods `(Console.WriteLine "Hello World")`
- `let` bindings

What's not done:
- String interpolation
- Macro system
- Add some useful aliases - e.g. `Console.WriteLine` should be aliased to `print`
- Ideas: Algebraic data types? Pattern Matching?

**Comment by waf** [comment]
Implemented anonymous functions, and the compiler can now produce DLLs

**Comment by waf** [comment]
Well, another hacknight, another lisp-hacking session. I'll be experimenting with adding [Paket tooling support](https://fsprojects.github.io/Paket/).

**Comment by waf** [comment]
just kidding, I'll be hacking on something else :smile: Still happy to talk about this if anyone is curious, though.
