### ISSUE TITLE
OpenFlight data analysis #scala

### ISSUE THREAD

**Issue by tao-pr** [bkkhack/hacknights#57]
Play around with some simple graph analysis on OpenFlight dataset (http://openflights.org/data.html) using Scala. I take this chance to learn Scala too (as a complete newbie).

**Comment by ches** [comment]
I can help on the Scala basics, you can probably help me on data science techniques :wink:

**Comment by tao-pr** [comment]
:metal:  :open_mouth: :metal: That would help me accelerating the early learning curve a lot.

**Comment by bkktimber** [comment]
Interesting topic. I am new to data science and Scala. Don't know how much I can do but I think here is good project to start with.

**Comment by tao-pr** [comment]
You're welcome to join and discuss :+1: 
Simple graph implementation / traversal / route finding would be nice to play with (in order to settle with the language)

**Comment by ap76ap** [comment]
I'm Interested to join in on this. I have no Scala experience, but have worked a lot with data in the past.

**Comment by tao-pr** [comment]
That will definitely be a great help.  :hushed: Feel free to join and share your ideas. :+1:

**Comment by ches** [comment]
https://github.com/starcolon/flights

and

https://gitter.im/bkkhack/scala

**Comment by tao-pr** [comment]
**Progress we made at #bkkhack**
- [x] We applied some Scala conventions. Now the project looks much more Scala-ish! 
- [x] We are moving away from `List` to `Map` (Hashmap). This will be updated soon. 
- [x] Participants are (hopefully) now be much more familiar with Scala :joy: 

Great thanks to @ches for lots of advices! Thanks everyone for joining too :+1: 
I would continue on this next time.

**Comment by tao-pr** [comment]
Reopen this again since the last hack mostly focused on learning Scala. This time it will involve more graph theory stuffs. (However, still as a Scala beginner :hamster:)

Same repo: https://github.com/starcolon/flights

I may this time try to implement _one of the following_ algorithms in Scala for OpenFlight data:
- [ ] Minimum spanning tree (for finding shortest connected routes among cities).
- [ ] Maximum flow (for finding the principal route from a city to another without direct flight).

**Comment by gpouilloux** [comment]
I'm interested to join you guys. I have a little experience of Scala so it's the opportunity to use it. Implemented few graph algorithms at school (https://github.com/gpouilloux/graphs-algorithms) and I want to learn more :)

**Comment by tao-pr** [comment]
@gpouilloux Awesome 👍  . Feel free to join next time (Thursday 30th). For the time being, you can check out the current implementation at (https://github.com/starcolon/flights). It's not obvious but, yes, we are using adjacency matrix to represent the flight graph.
