### ISSUE TITLE
Machine learning play with TensorFlow

### ISSUE THREAD

**Issue by statguy** [bkkhack/hacknights#63]
Play with TensorFlow

**Comment by chayapan** [comment]
which programming language background is a requisite for this?

**Comment by mishari** [comment]
Python

**Comment by tao-pr** [comment]
Interesting.  :)  What kind of data are you guys gonna play with?

**Comment by chayapan** [comment]
Can we use something from Quandl? https://www.quandl.com

**Comment by statguy** [comment]
@starcolon I would like to do some time-series of events predictions, basically what event would be the most probable to happen next given the past events

**Comment by chayapan** [comment]
@statguy  the training finally finished on my installation some time last night.

```

Epoch: 13 Train Perplexity: 36.703
Epoch: 13 Valid Perplexity: 122.850
Test Perplexity: 117.765
```

I'm getting on average 250 wps on Debian VPS with 2 cores and 4 GB RAM. Total runtime of the program is about 12-16 hours.

**Comment by tao-pr** [comment]
Hi guys,
Which repository are you playing around with? I'm interested to have a look too.

**Comment by chayapan** [comment]
Hi Tao,

We just ran the TensorFlow's Recurrent Neural Network example:
https://www.tensorflow.org/versions/r0.8/tutorials/recurrent/index.html

It's just a model testing / validation program, I think. The program,
"ptb_world_lm.py", can be located here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/models/rnn/ptb

~A

**Comment by aljones15** [comment]
Hi is this hack happening in the may event? If so can I join? Know Python and took a tensor flow course on udacity... Well,ok I didn't get past the first unit yet, but ya know.
