### ISSUE TITLE
BSD - Intro to JavaScript & PhaserJS

### ISSUE THREAD

**Issue by hunterwilliams** [bkkhack/hacknights#76]
If anyone is interested in learning some basic JavaScript or trying out [Phaser.js](http://phaser.io/) game development, I'll be covering the basics!

**Comment by TongWR** [comment]
Interested in this! Can do some JavaScript. Phaser looks powerful.

**Comment by carlfrie** [comment]
I'd love to learn some JS from a human instead of a book/website!
