### ISSUE TITLE
phonehome voting system for plone plugins

### ISSUE THREAD

**Issue by djay** [bkkhack/hacknights#77]

**Comment by djay** [comment]
Plone needs a way to see plugins are popular and often used together. Previous attempts got mixed results (thumbs up or down voting).

Instead we will create a script to run on any plone site which collects the plugin list and versions and posts it as a form to plone.org.

On plone.org we will create a rapido app which records this data along with the referrer domain. Based on this we will have system to rank popularity of plugins, what they are often used with, how recently they were used and what versions of plone they are compatible with. You might also be able to explore individual site "stacks" or users preferred plugins.

**Comment by jean** [comment]
I'm in :)

**Comment by jean** [comment]
I mostly just grunted, but Dylan very quickly got the necessary info from the quickinstaller tool via Python Script. We were pondering how we want to present collected data.
- top add-ons (versions)
- top combinations (people who have X install, often have Y too)
- how many add-ons on average
- out of date add-ons
- active vs inactive
- grouped geographically? by site? by user? (anonymised somehow)

**Comment by graffic** [comment]
I might join you guys if in the end Jean doesn't do the Hack on Trello API  and if there is space for a third :D

**Comment by djay** [comment]
cool @graffic . It's being written in rapido so it can be deployed to plone.org hopefull. You might want to read up on it. https://pypi.python.org/pypi/rapido.plone. but its very straight forward.
