### ISSUE TITLE
Transportation data analysis: how to spend ~$100 Google Cloud Platform credit in 2 hours

### ISSUE THREAD

**Issue by chayapan** [bkkhack/hacknights#78]
There are two tutorials I've been meaning to do, but have not:
1. Airlines dataset with Ipython / Spark
2. http://hortonworks.com/blog/data-science-apacheh-hadoop-predicting-airline-delays/
3. http://nbviewer.ipython.org/github/ofermend/IPython-notebooks/blob/master/blog-part-1.ipynb

or
1. Uber dataset with R
2. http://toddwschneider.com/posts/analyzing-1-1-billion-nyc-taxi-and-uber-trips-with-a-vengeance/
3. https://github.com/toddwschneider/nyc-taxi-data

I have some free GCP credits left and would like to find some fun way spend it ;)

Pre-requisites:
- Spark and Hadoop on Google Cloud Platform Documentation - https://cloud.google.com/hadoop/
- Setting Up PostgreSQL on Compute Engine - https://cloud.google.com/solutions/set-up-postgres#objectives

**Comment by ches** [comment]
Hi @chayapan, I see you're planning to attend again this month so in case you want to work on this again I'm leaving it open for others to find. If you want to do something else this time feel free to close it/move it to Done.
