### ISSUE TITLE
React-based frontend for ZerotierOne network controller

### ISSUE THREAD

**Issue by asyrique** [bkkhack/hacknights#79]
[ZeroTierOne](https://www.zerotier.com/) is an awesome C-based binary that creates an overlay network between any device on any network.

You interact with the binary via a JSON api, and the client already has a nice React-based GUI packaged with it. However, there's no GUI for the network controller side, which actually arbitrates networks and creates the connections between nodes.

I aim to get a rudimentary GUI up and running that allows visualization of the current nodes connected to a network controller and which networks they are on, whether they are authorized, and a rudimentary visualization of the networks managed by the network controller.

More info: 
- https://github.com/zerotier/ZeroTierOne
- https://github.com/zerotier/ZeroTierOne/tree/master/controller

**Comment by ches** [comment]
This is a pretty neat system, did you make any progress on the GUI project last time?
