### ISSUE TITLE
Manageable static site generator

### ISSUE THREAD

**Issue by abunashir** [bkkhack/hacknights#81]
There are lots of static site generator out there, almost in every case you need a developer to update or do minor modifications. Static site has fewer server-side dependencies, better performance, and superior security.

Personally, I think it's a good option for normal purpose website, but it's tough to get any non-tech customer on board as they can't have the ability to update or modify.

So, I was considering developing something that could somehow solve those limitations. My expertise area is Ruby, but I'm open to having any expert opinion and see if we can do something better together.

**Comment by thinking-twins** [comment]
By "update/modification", do you mean the frontend-design itself or the content?

Would be in for a discussion about this :)

**Comment by abunashir** [comment]
Both, for the beginning I would focus on content management portion but in the long run, we should support front-end design modification as well. We could have something similar to Shopify/WordPress theme customization.

Cool, let's have a talk, I'm sure we can figure out what would work best
