### ISSUE TITLE
4Clojure!

### ISSUE THREAD

**Issue by drawnwren** [bkkhack/hacknights#93]
4Clojure is a set of programming problems in Clojure. All the way from Basic to Expert. I'll be doing some, stop by and we can do some together!

**Comment by aljones15** [comment]
this sounds like fun or frustration.regardless I'm in. When is the next night?

**Comment by ches** [comment]
@aljones15 It's [this Thursday, the 30th](http://www.meetup.com/bkkhack/events/230863155/)—there's a waitlist but at this point I think those on it will likely get through.

**Comment by drawnwren** [comment]
If anyone is completely new to Clojure, I'd recommend at least setting up an IDE beforehand. I'm more than happy to help people, but there is a great guide for Emacs (the best editor for everything) here: http://www.braveclojure.com/getting-started/
If Emacs is a bit overwhelming, IntelliJ IDEA w/ Cursive (Community Edition is perfectly fine), Sublime, or Light Table are all more 'modern feeling' editors that are free and play nicely with Clojure.

**Comment by aljones15** [comment]
Am I on the wait list? Anyways see you this Thursday.

**Comment by aljones15** [comment]
ok looks like I am in. @DrawnWren I have vim with a syntax highlighter.

**Comment by jean** [comment]
@DrawnWren where are you ... ? :-)

**Comment by drawnwren** [comment]
Over at Orange! Sorry, had to get permissions worked out

**Comment by drawnwren** [comment]
Look for the laptop with the big black banksy sticker

**Comment by aljones15** [comment]
ok now up to 29 4clojures completed. Learned: I don't understand functional programming anywhere as well as I thought. Made a few functions using destructing it was awesome. Learned a bit about recursion in Clojure and that basic functional tasks like Distinct and especially flatten are more difficult to write than I thought (managed to finish both a bit later) all in all had a good time and learned alot. Advice for next time spend a little more time learning the language before trying the problems had no idea reduce could take 2 parameters i.e [] and the list for flatten..
