### ISSUE TITLE
JavaScript and Phaser.io game

### ISSUE THREAD

**Issue by nm2501** [bkkhack/hacknights#96]
Never used Phaser.io. I fancy trying it out and making a 2D game. Don't know what yet. You're welcome to join me.

**Comment by ches** [comment]
Folks from BSD Academy just led an introduction to Phaser at last month's hack night, too bad if you missed them :smile:  Maybe someone who followed along last month will be back and could give you a head start.

**Comment by nm2501** [comment]
I work at BSD Academy :D but I'm not the instructor who did Phaser last time. I'm just trying out Phaser for fun.
